export const AJAX_START = 'AJAX_START';
export const AJAX_FINISH = 'AJAX_FINISH';
export const AJAX_FAIL = 'AJAX_FAIL';
export const SET_SELECTED_PUBLICTASK = 'SET_SELECTED_PUBLICTASK';


export const DATA_RECEIVED = 'DATA_RECEIVED';
export const ENTITY_RECEIVED = 'ENTITY_RECEIVED'
export const RECEIVED_PERSISTED_ENTITY = 'RECEIVED_PERSISTED_ENTITY';
export const ENTITY_UPDATE = 'ENTITY_UPDATE';
